# This is a POST request to the /vectorize endpoint of our server
POST http://localhost:8000/vectorize HTTP/1.1

# The Host header specifies the host and port number of the server to which the request is being sent
Host: localhost:8000

# The Content-Type header indicates the media type of the resource in the request body
Content-Type: application/json

# The request body is a JSON object
{
    # "values" is an array of objects, each representing a record to be processed
    "values": [
      {
        # "id" is a unique identifier for the record
        "id": "0",

        "data":
           {
             # "url" is the URL of the PDF file to be processed
             "url": "https://testeastusdev001.blob.core.windows.net/customskillspdf/instruction-manual-fieldvue-dvc6200-hw2-digital-valve-controller-en-123052.pdf"
           }
      }
    ]
}
