# POST http://localhost:8000/createChunks HTTP/1.1
# Content-Type: application/json

# {
#     "values": [
#         {
#             "recordId": "0",
#             "data": {
#                 "url": "https://testeastusdev001.blob.core.windows.net/customskillspdf/instruction-manual-fieldvue-dvc6200-hw2-digital-valve-controller-en-123052.pdf"
#             },
#             "chunk_size": 1000,
#             "chunk_overlap": 100
#         }
#     ]
# }


POST https://customskill.yellowtree-64f92beb.eastus.azurecontainerapps.io/ HTTP/1.1
Content-Type: application/json

{
    "values": [
        {
            "recordId": "0",
            "data": {
                "url": "https://testeastusdev001.blob.core.windows.net/customskillspdf/instruction-manual-fieldvue-dvc6200-hw2-digital-valve-controller-en-123052.pdf"
            },
            "chunk_size": 1000,
            "chunk_overlap": 100
        }
    ]
}
